### ISSUE TITLE
[BUG] Unable to deserialize to MessageFailedCallback

### ISSUE THREAD

**Issue by LN-MDeRuscio** [Bandwidth/csharp-sdk#121]
### Checklist
 - [X] Have you provided a description of the bug?
 - [X] Have you provided your Environment information?
 - [X] Have you provided a sample code snippet?
 - [X] Have you provided a stack trace?
 - [X] Have you outlined the expected behavior?

### Description
When trying to deserialize a json string for the MessageFailedCallback class, a JsonSerializationException is thrown stating that the required property 'priority' is not found in the JSON string.

It appears the response provided by the Outbound message webhook does not include the priority property, but the class expects it to be included as it is marked required.

### Environment Information
 - OS Version: Windows 11
 - SDK Version: 11.1.0
 - Environment: .NET Core 8.0

### Sample Code Snippet

```csharp
var data = """
[
  {
    "type"          : "message-failed",
    "time"          : "2016-09-14T18:20:16Z",
    "description"   : "forbidden to country",
    "to"            : "+52345678903",
    "errorCode"     : 4432,
    "message"       : {
      "id"            : "14762070468292kw2fuqty55yp2b2",
      "time"          : "2016-09-14T18:20:16Z",
      "to"            : ["+12345678902"],
      "from"          : "+12345678901",
      "text"          : "",
      "applicationId" : "93de2206-9669-4e07-948d-329f4b722ee2",      
      "owner"         : "+12345678901",
      "direction"     : "out",
      "segmentCount"  : 1,      
      "tag":""
    }
  }
]
""";

var obj = JsonConvert.DeserializeObject<List<MessageFailedCallback>>(data);

```

### Stack Trace

Message: Required property 'priority' not found in JSON. Path '[0].message', line 19, position 5.
```shell
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
at UserQuery.Main(), line 25
```

### Expected Behavior
The outgoing message webhook body should deserialize to the MessageFailedCallback class if the content has the message-failed type.

### Suggested Fix
Make the Priority property on the MessageFailedCallbackMessage class nullable and remove 'IsRequired = true' from the DataMember attribute.

**Comment by ckoegel** [comment]
@LN-MDeRuscio 
Looks like this was improperly marked as `required` in our openapi spec, causing the auto-generated model to require it as well. I'll update our spec file so this gets fixed when the SDK auto-generates again on Tuesday (9/24). We should be able to release a fix for this on the same day. Thanks for finding this!

**Comment by LN-MDeRuscio** [comment]
Thank you for the update.

I also noticed it on the MessageSendingCallbackMessage class as well.
